name: Docker Image CI

on:
  push:
    branches: 
      - master

    tags:
      - v*

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Docker buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v3
      with:
        buildx-version: latest
        qemu-version: latest
    - name: Docker login
      env: 
        DOCKER_USERNAME: ${{ secrets.DOCKER_LOGIN }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASS }}
      run: echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}"
    - name: Build the Docker image
      run: docker buildx build .  --file Dockerfile --tag colemamd/motion-docker:latest --platform linux/arm/v7,linux/arm64,linux/amd64 --output "type=image,push=true"
